[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

# eth_rpc_url = "http://127.0.0.1:8545"
eth_rpc_url = "https://mainnet.infura.io/v3/6f142304895f4ee9b2ca4e71aeff76bf"
sender = "0xDe0476793ff6BBf931B5FD8586E275B43Be195C2"
# gas_limit = 9223372036854775807
# gas_price = 0
etherscan_api_key = "8TR2MGSFE5V8NGZUB713B5UEG4P14M4IZG"
